[/Script/Engine.RendererSettings]
; DISABLING RayTracing for Linux Performance
r.RayTracing=False
r.RayTracing.RayTracingProxies.ProjectEnabled=False
r.Shadow.Virtual.Enable=0
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=0
r.Lumen.DiffuseIndirect.Allow=0
r.Nanite=0

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
; Force Vulkan SM5 (More stable/faster than SM6 on some drivers)
-TargetedRHIs=SF_VULKAN_SM6
+TargetedRHIs=SF_VULKAN_SM5
